---
#Configuracion del Servidor
server:
  error:
    include-message: always
    include-binding-errors: always
#Configuracion del log
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: HH:mm:ss

#Suprimir el banner de Spring
spring:
  main:
    banner-mode: off
  #Configuracion de MySQL
  datasource:
    password: admin
    url: jdbc:mysql://still-mapper-369012:us-central1:facturador-db-instance/facturador_db?useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 280000
      max-active: 50
      max-idle: 20
      min-idle: 15
  #Aclaraciones para JPA
  jpa:
    #Lenguaje
    database: MYSQL
    #Dialecto
    database-platform: org.hibernate.dialect.MySQL5Dialect
    #Mostrar codigo SQL
    show-sql: true
    #Desactivar OpenEntityManagerInViewInterceptor (Recomendable)
    open-in-view: false
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        format_sql: true
  #Configuracion de servlet para tamaño de la request
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
...


