---
#Configuracion del Servidor
server:
  error:
    include-message: always
    include-binding-errors: always
#Configuracion del log
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: HH:mm:ss

#Suprimir el banner de Spring
spring:
  main:
    banner-mode: off
  #Configuracion de MySQL
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/facturador_db?useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Aclaraciones para JPA
  jpa:
    #Lenguaje
    database: MYSQL
    #Dialecto
    database-platform: org.hibernate.dialect.MySQL5Dialect
    #Mostrar codigo SQL
    show-sql: false
    #Desactivar OpenEntityManagerInViewInterceptor (Recomendable)
    open-in-view: false
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        format_sql: true
...


