#Los --- y ... indican cuando inicia y termina el YML
---
#Configuracion del log
logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: HH:mm:ss

#Cofiguracion Spring
spring:
  main:
    banner-mode: off
  #Configuracion de MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/facturador-mas?useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  #Configuracion de Spring Security
  security:
    user:
      name: user
      password: password
#Configuracion de JWT
security:
  jwt:
    secret: thisIsASecrectMyFriend
    issuer: Main
    #Este valor dice que la sesion dura dos dias (Para sacarlo "horas * 3600000")
    ttlMillis: 172800000
...
